export const warrantyConfig = {
    title: "Warranties",
    initialFilters: {
        customer: [],
        product: [],
        color: [],
        size: [],
        duration: [],
        start_date: {},
        end_date: {},
        status: [],
    },
    fields: [
        {
            key: "invoice_number",
            label: "Invoice Number",
            accessorFn: (row) => row.sale?.invoice_number || "N/A",
            filterType: "checkbox",
            responsive: true,
        },
        {
            key: "customer",
            label: "Customer",
            accessorFn: (row) => row.sale?.customer?.name ?? "N/A",
            filterType: "checkbox",
            responsive: true,
        },
        {
            key: "product",
            label: "Product",
            accessorFn: (row) => row.product?.name ?? "N/A",
            filterType: "checkbox",
            responsive: true,
        },
        {
            key: "color",
            label: "Color",
            accessorFn: (row) => row.variant?.color_name?.name ?? "N/A",
            filterType: "checkbox",
            responsive: true,
        },
        {
            key: "size",
            label: "Size",
            accessorFn: (row) => row.variant?.variation_size?.size ?? "N/A",
            filterType: "checkbox",
            responsive: true,
        },
        {
            key: "duration",
            label: "Duration",
            accessorFn: (row) => String(row.duration || "N/A"),
            filterType: "checkbox",
            responsive: true,
        },
        {
            key: "start_date",
            label: "Start Date",
            accessorFn: (row) => row.start_date || "N/A",
            filterType: "date",
            responsive: true,
        },
        {
            key: "end_date",
            label: "End Date",
            accessorFn: (row) => row.end_date || "N/A",
            filterType: "date",
            responsive: true,
        },
        {
            key: "status",
            label: "Status",
            accessorFn: (row) => String(row.status || "N/A"),
            filterType: "checkbox",
            responsive: true,
        },
    ],
    filtersConfig: ["customer", "product", "color", "status"],
    actionConfig: {
        buttons: [
            {
                icon: "fa7-solid:file-invoice",
                className:
                    "text-blue-500 hover:text-blue-700 sm:text-sm text-xs",
                onClick: (row) => (location.href = `/warranty/card/${row.id}`),
                title: "Warranty Card",
            },
            {
                icon: "mdi:delete",
                className: "text-red-500 hover:text-red-700 sm:text-sm text-xs",
                onClick: (row) => openDeleteModal(row),
                title: "Delete",
                condition: (row, perms) => perms.includes("pos-manage.delete"),
            },
        ],
    },
    mapping: {
        sl: (row, idx) => String(idx + 1),
        invoice_number: (row) => row.sale?.invoice_number || "N/A",
        customer: (row) => row.sale?.customer?.name ?? "N/A",
        product: (row) => row.product?.name ?? "N/A",
        color: (row) => row.variant?.color_name?.name ?? "N/A",
        size: (row) => row.variant?.variation_size?.size ?? "N/A",
        duration: (row) => String(row.duration || "N/A"),
        start_date: (row) => row.start_date || "N/A",
        end_date: (row) => row.end_date || "N/A",
        status: (row) => String(row.status || "N/A"),
    },
    onFieldChange: null,
};
